version: '3'
services:
    db:
        image: microsoft/mssql-server-linux
        environment:
            SA_PASSWORD: ${SQL_SERVER_PASSWORD}
            ACCEPT_EULA: Y
        ports:
            - '14333:1433'